### ISSUE TITLE
App does not ask for confirmation when logging in with phone number

### ISSUE THREAD

**Issue by alejo4373** [alejo4373/Bite-web#1]
Apps should ask for confirmation via pop up because standard sms rates apply when signing via phone number. 

Ask for confirmation via `window.alert` before sending login request and only if user accepts.

**Comment by Radhesh-Sarma** [comment]
@alejo4373 I want to work on this. Please assign the issue to me

**Comment by Radhesh-Sarma** [comment]
@alejo4373 I don't have src/firebase/config file , hence not able to setup the project here 
This file is in the gitignore , hence you are not uploading it .
I am hence getting this message
./src/firebase/index.js
Module not found: Can't resolve './config'

**Comment by alejo4373** [comment]
Hi @Radhesh-Sarma thanks for the interest and I'm sorry for the delay. Check your inbox, I sent you an email.

**Comment by Radhesh-Sarma** [comment]
@alejo4373  I have fixed this issue and made a pull request. Please review.

**Comment by alejo4373** [comment]
Thank you for fixing this @Radhesh-Sarma! Really appreciate it!
